<a href="https://colab.research.google.com/github/akashmodak97/Genre-Detection-Of-Bengali-Songs-Based-On-Audio-Data/blob/master/Music_Genre_Classification_using_LSTM_based_on_audio_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Created By Akash Modak ##
## Date 25/06/2020 Time 21:05 ##
import numpy as np 
import pandas as pd
import csv
import io
from google.colab import files
# uploaded = files.upload()
# d = pd.read_csv(io.BytesIO(uploaded['combined1.csv']))

# features = []
# names = []
# print(data)
# with open('final.csv','rt')as f:
#   data = csv.reader(f)
#   for row in data:
#     features.append(np.array(row[0:]))
  
# # print(uploaded['combined1.csv'])
# # print(d)
# features = np.array(features)
# print(features)
df_train = pd.read_csv('combined2.csv')
print('train set: {0}'.format(df_train.shape))
df_train.head(10)

train set: (1373, 56)


song_id       tempo  total_beats  ...  frame_std  frame_var  label
0        1  117.453835       143490  ...   1.092411   1.193362      3
1        2  129.199219       164643  ...   4.649220  21.615245      3
2        3  151.999081       199193  ...   1.129929   1.276739      3
3        4  151.999081       161883  ...   3.537997  12.517425      3
4        5  161.499023       210099  ...   1.572752   2.473548      3
5        6  143.554688       183554  ...   1.372578   1.883970      3
6        7  107.666016       138107  ...   1.282054   1.643663      3
7        8  129.199219       157403  ...   3.403311  11.582525      3
8        9  135.999178       169544  ...   1.354491   1.834647      3
9       10   99.384014       126673  ...   1.002803   1.005614      3

[10 rows x 56 columns]

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot as plt
plt.style.use('dark_background')

from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Dropout, Embedding, LSTM

In [ ]:
training_set = df_train.iloc[:,1:54].values

In [ ]:
import random
random.shuffle(training_set)
X_test = training_set[-100:]
training_set = training_set[:-100]
print(training_set)
# print(X_test)
X_test_final = []
for i in range (60,100):
  X_test_final.append(X_test[i-60:i,0])

[[1.17453835e+02 1.43490000e+05 1.25868421e+03 ... 8.83668200e-03
  1.76587755e+00 1.09241126e+00]
 [1.29199219e+02 1.64643000e+05 1.27630233e+03 ... 7.39908000e-04
  8.46715646e+00 4.64921988e+00]
 [1.17453835e+02 1.43490000e+05 1.25868421e+03 ... 8.83668200e-03
  1.76587755e+00 1.09241126e+00]
 ...
 [9.57031250e+01 1.19832000e+05 1.31683516e+03 ... 5.66691000e-04
  4.09251701e+00 1.10483743e+00]
 [1.72265625e+02 2.19012000e+05 1.32734546e+03 ... 1.03351400e-03
  4.34561451e+00 1.18132931e+00]
 [1.43554688e+02 1.70821000e+05 1.24686861e+03 ... 1.66982000e-04
  2.10372789e+00 1.34151065e+00]]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)
print(training_set_scaled)

[[0.35064935 0.38152352 0.33738388 ... 0.38082447 0.01568704 0.01774758]
 [0.42857143 0.4808609  0.35541754 ... 0.0314006  0.2403659  0.20791217]
 [0.35064935 0.38152352 0.33738388 ... 0.38082447 0.01568704 0.01774758]
 ...
 [0.20634921 0.27042232 0.39690641 ... 0.02392526 0.09369404 0.01841195]
 [0.71428571 0.73618514 0.40766459 ... 0.04407145 0.10217984 0.02250158]
 [0.52380952 0.50987363 0.3252896  ... 0.00667545 0.0270144  0.03106567]]


In [ ]:
X_train = []
y_train = []
for i in range(60, 1272):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
    
    # X_train.append(training_set[i-60:i, 0])
    # y_train.append(training_set[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_test_final = np.array(X_test_final)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test_final = np.reshape(X_test_final, (X_test_final.shape[0],X_test_final.shape[1],1))
x_val = X_train[-100:]
y_val = y_train[-100:]
X_train = X_train[:-100]
y_train = y_train[:-100]
# print(X_train)

In [ ]:
regressor = Sequential()

regressor.add(LSTM(units = 64, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 64, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 64))
# regressor.add(Dropout(0.2))

regressor.add(Dense(units = 64, activation='relu'))
regressor.add(Dropout(0.1))
regressor.add(Dense(64, activation='relu'))


# regressor.add(Dense(32,activation='softmax'))

regressor.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4), metrics=['accuracy'])

regressor.fit(X_train, y_train, epochs = 100, validation_data=(x_val,y_val), batch_size = 32)

Train on 1112 samples, validate on 100 samples
Epoch 1/100
1112/1112 [==============================] - 6s 5ms/step - loss: 0.6933 - accuracy: 0.0171 - val_loss: 0.6931 - val_accuracy: 0.3500
Epoch 2/100
1112/1112 [==============================] - 4s 4ms/step - loss: 0.6931 - accuracy: 0.3867 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 3/100
1112/1112 [==============================] - 4s 4ms/step - loss: 0.6931 - accuracy: 0.7050 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 4/100
1112/1112 [==============================] - 4s 4ms/step - loss: 0.6931 - accuracy: 0.8219 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 5/100
1112/1112 [==============================] - 4s 4ms/step - loss: 0.6931 - accuracy: 0.8759 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 6/100
1112/1112 [==============================] - 4s 4ms/step - loss: 0.6931 - accuracy: 0.9074 - val_loss: 0.6931 - val_accuracy: 1.0000
Epoch 7/100
1112/1112 [==============================] - 4s 4ms/step - loss: 0.6931

In [ ]:
predict_output = regressor.predict(X_test_final)

In [ ]:
print(predict_output)

[[0.         0.16574945 0.         ... 0.         0.02686475 0.04035877]
 [0.         0.16595042 0.         ... 0.         0.02677922 0.04036916]
 [0.         0.16570547 0.         ... 0.         0.02695834 0.04071589]
 ...
 [0.         0.16499    0.         ... 0.         0.02707372 0.04000176]
 [0.         0.16517092 0.         ... 0.         0.02697506 0.03980707]
 [0.         0.16547696 0.         ... 0.         0.02681224 0.03998208]]
